title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://ucla-imls-open-sci.info/UCLA-imls-docs

aux_links:
  Template Repository: https://github.com/ucla-imls-open-sci/UCLA-imls-docs
