name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Ruby Environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 0 # Increment this number to reset cached gems

      - name: Unfreeze Bundler (if necessary)
        run: bundle config set frozen false

      - name: Install Dependencies
        run: bundle install --no-deployment --without development test

      - name: Build with Jekyll
        run: bundle exec jekyll build

      - name: Verify Updated Gemfile.lock (optional)
        if: always()
        run: |
          if git diff --quiet Gemfile.lock; then
            echo "Gemfile.lock is up-to-date.";
          else
            echo "Gemfile.lock has been modified. Review changes locally.";
          fi
