name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Ruby Environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: false # Disable automatic bundler cache to control behavior

      - name: Install Dependencies
        run: |
          bundle config set frozen false
          bundle install

      - name: Build with Jekyll
        run: bundle exec jekyll build
